### ISSUE TITLE
As developer I want to start evaluation runs on my model so that I can gain metrics from them.

### ISSUE THREAD

**Issue by LauranEkeren** [LauranEkeren/Automatic-Score-Calculator#12]

**Comment by LauranEkeren** [comment]
- [ ] Research on how to run evaluation runs on yolov7 #13 
- [ ] Setup the environment for evaluation runs #14 
- [ ] Label the evaluation set #15 
- [ ] Run evaluations #16 
- [ ] Compare metrics #17
